steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/supabase-backup:latest', '.']
    dir: cloudrun/backup

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/supabase-backup:latest']

images:
  - 'gcr.io/$PROJECT_ID/supabase-backup:latest'
